// WebApp/HomeAutomation/homeautomation.web.react/src/Components/SensorItem.tsx
import { Box, Button, TextField } from '@mui/material';
import React, { useEffect, useState } from 'react';
import { Sensor } from '../api/models/Sensor';
import { Create, Load, Update } from '../api/resources/SensorApi';

type SensorItemProps =
{
	sensorId: number
	updateSensors: () => Promise<void>
}

function SensorItem({ sensorId, updateSensors }: SensorItemProps) {
	const [sensor, setSensor] = useState<Sensor>({} as Sensor);

	async function submit() {
		if (sensor.id) {
			await Update(sensor);
		}
		else {
			await Create(sensor);
		}

		await updateSensors();
	}

	async function loadSensor(sensorId: number) {
		if (sensorId > 0) {
			setSensor(await Load(sensorId));
		}
	}


	useEffect(() => {
		loadSensor(sensorId);
	}, [sensorId]);

	return (
		<Box
			component="form"
			sx={{
				'& .MuiTextField-root': { m: 1, width: '25ch' },
			}}
			noValidate
			autoComplete="off"
		>
			<div>
				<TextField
					required
					InputLabelProps={{ shrink: true }}
					id="outlined-required"
					label="Name"
					value={sensor?.name ?? ""}
					onChange={(e) => setSensor(prevState => {
						return {
							...prevState,
							name: e.target.value
						};
					})}
				/>
				<TextField
					required
					InputLabelProps={{ shrink: true }}
					id="outlined-required"
					label="SensorTypeID"
					type="number"
					value={sensor?.sensorTypeID ?? ""}
					onChange={(e) => setSensor(prevState => {
						return {
							...prevState,
							sensorTypeID: Number(e.target.value)
						};
					})}
				/>
				<TextField
					required
					InputLabelProps={{ shrink: true }}
					id="outlined-required"
					label="LocationId"
					type="number"
					value={sensor?.locationID ?? ""}
					onChange={(e) => setSensor(prevState => {
						return {
							...prevState,
							locationID: Number(e.target.value)
						};
					})}
				/>
				<TextField
					required
					InputLabelProps={{ shrink: true }}
					id="outlined-required"
					label="CodeVersion"
					type="number"
					value={sensor?.codeVersion ?? ""}
					onChange={(e) => setSensor(prevState => {
						return {
							...prevState,
							codeVersion: Number(e.target.value)
						};
					})}
				/>
				<Button variant="outlined" onClick={submit}>Submit</Button>
			</div>
		</Box>
	);
}

export default SensorItem;

// WebApp/HomeAutomation/HomeAutomation.Web.Vue/src/components/SensorItem.vue
<script lang="ts" setup>
	import { defineEmits, defineProps, reactive, watch } from 'vue';
	import { Sensor } from '../api/models/Sensor';
	import { Load, Create, Update } from '../api/resources/SensorApi';

	const emit = defineEmits(['reLoad'])

	const props = defineProps({
		id: {
			type: Number, default: -1
		}
	});

	let data = reactive({ sensor: {} as Sensor });

	watch(() => props.id, async () =>
	{
		data.sensor = await Load(props.id);
		console.log(data.sensor);
	});

	async function submit() {
		console.log(data.sensor);

		if (data.sensor.id) {
			await Update(data.sensor);
		}
		else {
			await Create(data.sensor);
		}

		emit('reLoad');
	}
</script>

<template>
	<div>
		<input type="hidden" v-model="data.sensor.id" /><br />

		<label>Name</label>
		<input type="text" v-model="data.sensor.name" /><br />

		<label>SensorTypeId</label>
		<input type="text" v-model.number="data.sensor.sensorTypeID" /><br />

		<label>LocationId</label>
		<input type="text" v-model.number="data.sensor.locationID" /><br />

		<label>Code version</label>
		<input type="text" v-model.number="data.sensor.codeVersion" />

		<button @click="submit">Submit</button>
	</div>
</template>
