// WebApp/HomeAutomation/HomeAutomation.Web.Vue/src/components/SensorItems.vue
<script lang="ts" setup>
	import { ref, reactive, onMounted } from 'vue';
	import SensorItem from './SensorItem.vue';

	import { LoadAll, Delete } from '../api/resources/SensorApi';
	import { Sensor } from '../api/models/Sensor';

	console.log('SensorItems');
	let currentPage = ref(1);
	let totalPages = ref(0);

	let sensors = reactive({ values: [] as Sensor[] });
	let id = ref(0);

	const loadSensors = async () => {
		sensors.values = await LoadAll();
	}

	const edit = (sensorId: number) => {
		id.value = sensorId;
	}

	const remove = async (sensorId: number) => {
		await Delete(sensorId);
		await loadSensors();
	}

	onMounted(async () => {
		await loadSensors();
	});

</script>

<template>
	<h1>Sensor List</h1>
	<SensorItem :id="id" @reLoad="loadSensors" />
	<VTable :data="sensors.values"
			:pageSize="10"
			v-model:currentPage="currentPage"
			@totalPagesChanged="totalPages = $event"
			class="table">
		<template #head>
			<tr>
				<th>Name</th>
				<th>SensorTypeID</th>
				<th>CodeVerison</th>
				<th>Edit</th>
				<th>Delete</th>
			</tr>
		</template>
		<template #body="{rows}">
			<tr v-for="row in rows" :key="row.id">
				<td>{{ row.name }}</td>
				<td>{{ row.sensorTypeID }}</td>
				<td>{{ row.codeVersion }}</td>
				<td><i @click="edit(row.id)" role="button" class="bi bi-pen"></i></td>
				<td><i @click="remove(row.id)" role="button" class="bi bi-trash"></i></td>
			</tr>
		</template>
	</VTable>
	<VTPagination v-model:currentPage="currentPage"
				:total-pages="totalPages"
				:boundary-links="true" />
</template>

// WebApp/HomeAutomation/homeautomation.web.react/src/Components/SensorItems.tsx
import React, { useEffect, useState } from 'react';
import { render } from 'react-dom';
import { Sensor } from '../api/models/Sensor';
import { Delete, LoadAll } from '../api/resources/SensorApi';
import Table from '@mui/material/Table';
import TableBody from '@mui/material/TableBody';
import TableCell from '@mui/material/TableCell';
import TableContainer from '@mui/material/TableContainer';
import TableHead from '@mui/material/TableHead';
import TableRow from '@mui/material/TableRow';
import Paper from '@mui/material/Paper';
import SensorItem from './SensorItem';

function SensorItems() {
	const [sensors, setSensors] = useState<Sensor[]>([]);
	const [sensorId, setSensorId] = useState<number>(-1);

	const loadSensors = async () => {
		setSensors(await LoadAll());
	}

	const remove = async (sensorId: number) => {
		await Delete(sensorId);
		await loadSensors();
	}

	useEffect(() => { loadSensors(); }, []);

	return (
		<div>
			<SensorItem sensorId={sensorId} updateSensors={loadSensors} />
			<TableContainer component={Paper}>
				<Table sx={{ minWidth: 650 }} aria-label="simple table">
					<TableHead>
						<TableRow>
							<TableCell>Name</TableCell>
							<TableCell>Sensor type ID</TableCell>
							<TableCell>Code version</TableCell>
							<TableCell>Edit</TableCell>
							<TableCell>Delete</TableCell>
						</TableRow>
					</TableHead>
					<TableBody>
						{sensors.map((row) => (
							<TableRow
								key={row.id}
								sx={{ '&:last-child td, &:last-child th': { border: 0 } }}
							>
								<TableCell component="th" scope="row">
									{row.name}
								</TableCell>
								<TableCell align="right">{row.sensorTypeID}</TableCell>
								<TableCell align="right">{row.codeVersion}</TableCell>
								<TableCell align="right"><button onClick={() => { setSensorId(row.id) }}>Edit</button></TableCell>
								<TableCell align="right"><button onClick={() => { remove(row.id) }}>Delete</button></TableCell>
							</TableRow>
						))}
					</TableBody>
				</Table>
			</TableContainer>
		</div>
	);


}

export default SensorItems;
