// WebApp/HomeAutomation/HomeAutomation.Web.Vue/src/components/SensorItem.vue
<script lang="ts" setup>
	import { defineEmits, defineProps, reactive, watch } from 'vue';
	import { Sensor } from '../api/models/Sensor';
	import { Load, Create, Update } from '../api/resources/SensorApi';

	const emit = defineEmits(['reLoad'])

	const props = defineProps({
		id: {
			type: Number, default: -1
		}
	});

	let data = reactive({ sensor: {} as Sensor });

	watch(() => props.id, async () =>
	{
		data.sensor = await Load(props.id);
		console.log(data.sensor);
	});

	async function submit() {
		console.log(data.sensor);

		if (data.sensor.id) {
			await Update(data.sensor);
		}
		else {
			await Create(data.sensor);
		}

		emit('reLoad');
	}
</script>

<template>
	<div>
		<input type="hidden" v-model="data.sensor.id" /><br />

		<label>Name</label>
		<input type="text" v-model="data.sensor.name" /><br />

		<label>SensorTypeId</label>
		<input type="text" v-model.number="data.sensor.sensorTypeID" /><br />

		<label>LocationId</label>
		<input type="text" v-model.number="data.sensor.locationID" /><br />

		<label>Code version</label>
		<input type="text" v-model.number="data.sensor.codeVersion" />

		<button @click="submit">Submit</button>
	</div>
</template>

// WebApp/HomeAutomation/homeautomation.web.angular/src/app/sensor-item/sensor-item.component.ts
import { Component, EventEmitter, Input, OnInit, Output, SimpleChanges } from '@angular/core';
import { Sensor } from '../api/models/Sensor';
import { SensorApi } from '../api/resources/SensorApi';

@Component({
  selector: 'app-sensor-item',
  templateUrl: './sensor-item.component.html',
  styleUrls: ['./sensor-item.component.css']
})
export class SensorItemComponent implements OnInit {
  @Input() id: number = 0;
  @Output() updateSensors = new EventEmitter();

  public sensor: Sensor = {} as Sensor;

  constructor(private sensorApi: SensorApi) { }

  ngOnInit(): void {
  }

  ngOnChanges(changes: SimpleChanges) {
    if (changes['id'].currentValue > 0) {
      this.sensorApi.Load(changes['id'].currentValue).subscribe((data: any) => {
        this.sensor = data.value;
      });
    }
  }

  saveSensor() {
    if (this.id > 0) {
      this.sensorApi.Update(this.sensor).subscribe(() => this.updateSensors.emit());
    }
    else {
      this.sensorApi.Create(this.sensor).subscribe(() => this.updateSensors.emit());
    }
  }
}

<mat-form-field class="example-full-width" appearance="fill">
  <mat-label>Name</mat-label>
  <input matInput [(ngModel)]="sensor.name">
</mat-form-field>

<mat-form-field class="example-full-width" appearance="fill">
  <mat-label>Location ID</mat-label>
  <input matInput [(ngModel)]="sensor.locationID" type="number">
</mat-form-field>

<mat-form-field class="example-full-width" appearance="fill">
  <mat-label>Sensor type ID</mat-label>
  <input matInput [(ngModel)]="sensor.sensorTypeID" type="number">
</mat-form-field>

<mat-form-field class="example-full-width" appearance="fill">
  <mat-label>Code version</mat-label>
  <input matInput [(ngModel)]="sensor.codeVersion" type="number">
</mat-form-field>

<button (click)="saveSensor()">Submit</button>
